### ISSUE TITLE
platform independent Java executable file (.jar) for Ronja

### ISSUE THREAD

**Issue by ChessGUI** [dykstrom/ronja#1]
Can you build such a jar-file please? Arena, ChessGUI and WinBoard  are supporting such a file.

http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

**Comment by sandermvdb** [comment]
You can add this jar to the releases tab of github. And I would also give it a specific versionnumber if I were you.

**Comment by dykstrom** [comment]
I am working on adding some basic time management to the chess engine. After that I will build a release and publish it on GitHub. So it will happen in due time...
