### ISSUE TITLE
Java .exe-file by Roman Koldaev

### ISSUE THREAD

**Issue by ChessGUI** [dykstrom/ronja#2]
The author of SJCE https://sourceforge.net/projects/sjce/ created a jar-file here:
[ronja.zip](https://github.com/dykstrom/ronja/files/769265/ronja.zip) - no engine´s output is visible on Arena GUI http://www.playwitharena.com/ - perhaps a sensible time-management is missing

**Comment by dykstrom** [comment]
Thanks for the interest you show in my chess engine! The lack of time management is precisely why I have _not_ published any release of it yet. I am working on that in a branch of the project. When I have some basic time management in place I will build a 0.6.0 release. As for Arena, I have not tried that program for years, so I'm not surprised there are issues. I will look into that later.

**Comment by ChessGUI** [comment]
What is your current number of release? Ron from CCWiki would add it here: http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:chess_engine_list

by the way: UCI-protocol (for further versions) ~ http://www.shredderchess.com/download.html and http://download.shredderchess.com/div/uci.zip
