### ISSUE TITLE
Recompiling for newer Java versions

### ISSUE THREAD

**Issue by rwbc** [dykstrom/ronja#6]
It would be nice, if you could recompile Ronja 0.60 and 0.70 for newer Java versions, because they rely on deprecated libraries. Thanks a lot.
http://talkchess.com/forum3/viewtopic.php?p=780726#p780726

**Comment by dykstrom** [comment]
I guess that would be a good idea. I'll see what I can do. However, it is not as simple as just recompiling with Java 11, because they have made substantial changes to Java 11 compared to the older versions.

**Comment by dykstrom** [comment]
Now there is a release - 0.8.0 - that targets Java 11. It is the same as release 0.7.0 but modified to work with Java 11.
